contrib/wdisplays: add replaces=wcm to avoid file conflict
(37/38) Installing wdisplays (1.1.1-r0)
ERROR: wdisplays-1.1.1-r0: trying to overwrite usr/bin/wdisplays owned by wcm-0.8.0-r0.
ERROR: wdisplays-1.1.1-r0: trying to overwrite usr/share/applications/network.cycles.wdisplays.desktop owned by wcm-0.8.0-r0.
ERROR: wdisplays-1.1.1-r0: trying to overwrite usr/share/icons/hicolor/scalable/apps/network.cycles.wdisplays.svg owned by wcm-0.8.0-r0.
(38/38) Upgrading wcm (0.8.0-r0 -> 0.8.0-r1)