main/llvm: backport libcxx fix for static in constexpr
The pre-patch behavior is technically only allowed since C++23
while these are C++20. LLVM accepts this but GCC fails with
the following:

/usr/include/c++/v1/__algorithm/equal.h:250:25: error: '__both_random_access' defined 'static' in 'constexpr' function only available with '-std=c++23' or '-std=gnu++23' [-Wtemplate-body]
  250 |   static constexpr bool __both_random_access =

This fixes -std=c++20 (default) for GCC.

No rebuild, will make it through in .8.